workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS release
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.ipa

  android-release:
    name: Android Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      android: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build Android AAB
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
