name: boui_songs
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^4.7.1
  firebase_core: ^2.13.1
  cupertino_icons: ^1.0.8
  firebase_auth: ^4.16.0
  fluttertoast: ^8.2.4
  provider: ^6.0.5
  get: ^4.6.5

  # Audio playback
  audioplayers: ^5.2.0
  flutter_animate: ^4.5.2
  flutter_launcher_icons: ^0.14.3
  url_launcher: ^6.0.20
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0  # Added for loading effects

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.jpg
    - assets/logo.png
    - assets/unikodex_logo.jpg
    - assets/placeholder.jpg
    - assets/placeholder.png
  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"
  adaptive_icon_background: "#ffffff" # Optional for Android
  adaptive_icon_foreground: "assets/logo.jpg" # Optional for Android
