// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5m8X1mawqZKdbota0Pq3ePvKWkYwJlvg',
    appId: '1:592118847989:web:014a7798a8c188ee0668bc',
    messagingSenderId: '592118847989',
    projectId: 'boui-songs-4be1e',
    authDomain: 'boui-songs-4be1e.firebaseapp.com',
    storageBucket: 'boui-songs-4be1e.firebasestorage.app',
    measurementId: 'G-NQ52M7XD10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Ld9B6wQNw9Xu0hVsdKCOdskbdafCf-U',
    appId: '1:592118847989:android:aaf0c3d80b28351e0668bc',
    messagingSenderId: '592118847989',
    projectId: 'boui-songs-4be1e',
    storageBucket: 'boui-songs-4be1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJl-cogwzMrx0D6inrk8mqIV5JORSx5Zc',
    appId: '1:592118847989:ios:3a5638e8085f0b000668bc',
    messagingSenderId: '592118847989',
    projectId: 'boui-songs-4be1e',
    storageBucket: 'boui-songs-4be1e.firebasestorage.app',
    iosBundleId: 'com.boui.songs.app.bouiSongs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJl-cogwzMrx0D6inrk8mqIV5JORSx5Zc',
    appId: '1:592118847989:ios:3a5638e8085f0b000668bc',
    messagingSenderId: '592118847989',
    projectId: 'boui-songs-4be1e',
    storageBucket: 'boui-songs-4be1e.firebasestorage.app',
    iosBundleId: 'com.boui.songs.app.bouiSongs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5m8X1mawqZKdbota0Pq3ePvKWkYwJlvg',
    appId: '1:592118847989:web:6f0b024445ac85cf0668bc',
    messagingSenderId: '592118847989',
    projectId: 'boui-songs-4be1e',
    authDomain: 'boui-songs-4be1e.firebaseapp.com',
    storageBucket: 'boui-songs-4be1e.firebasestorage.app',
    measurementId: 'G-M3Z3VR2KKZ',
  );
}
